Public Class FBXCamera
  Inherits FBXValue
  Private sPiModelName As String = "Camerax01"

  Public Sub New()
    Me.SetValue("Version", "232")
    Me.SetValue("MultiLayer", "0")
    Me.SetValue("MultiTake", "0")
    Me.SetValue("Shading", "T")
    Me.SetValue("Culling", """CullingOff""")
    Me.SetValue("TypeFlags", """Camera""")
    Me.SetValue("GeometryVersion", "124")
    Me.SetValue("Position", "0, 0, 0")
    Me.SetValue("Up", "0,1,0")
    Me.SetValue("LookAt", "100, 0 ,0")
    Me.SetValue("ShowInfoOnMoving", "1")
    Me.SetValue("ShowAudio", "0")
    Me.SetValue("AudioColor", "0,1,0")
    Me.SetValue("CameraOrthoZoom", "1")
    Me.SetValue("NodeAttributeName", """NodeAttribute::" & Me.ModelName & "_ncl1_1""")

    Me.SetProperty("QuaternionInterpolate", "bool", "", 0)
    Me.SetProperty("RotationOffset", "Vector3D", "", 0, 0, 0)
    Me.SetProperty("RotationPivot", "Vector3D", "", 0, 0, 0)
    Me.SetProperty("ScalingOffset", "Vector3D", "", 0, 0, 0)
    Me.SetProperty("ScalingPivot", "Vector3D", "", 0, 0, 0)
    Me.SetProperty("TranslationActive", "bool", "", 0)
    Me.SetProperty("TranslationMin", "Vector3D", "", 0, 0, 0)
    Me.SetProperty("TranslationMax", "Vector3D", "", 0, 0, 0)
    Me.SetProperty("TranslationMinX", "bool", "", 0)
    Me.SetProperty("TranslationMinY", "bool", "", 0)
    Me.SetProperty("TranslationMinZ", "bool", "", 0)
    Me.SetProperty("TranslationMaxX", "bool", "", 0)
    Me.SetProperty("TranslationMaxY", "bool", "", 0)
    Me.SetProperty("TranslationMaxZ", "bool", "", 0)
    Me.SetProperty("RotationOrder", "enum", "", 0)
    Me.SetProperty("RotationSpaceForLimitOnly", "bool", "", 0)
    Me.SetProperty("RotationStiffnessX", "double", "", 0)
    Me.SetProperty("RotationStiffnessY", "double", "", 0)
    Me.SetProperty("RotationStiffnessZ", "double", "", 0)
    Me.SetProperty("AxisLen", "double", "", 10)
    Me.SetProperty("PreRotation", "Vector3D", "", -90, 0, 0)
    Me.SetProperty("PostRotation", "Vector3D", "", 0, 0, 0)
    Me.SetProperty("RotationActive", "bool", "", 1)
    Me.SetProperty("RotationMin", "Vector3D", "", 0, 0, 0)
    Me.SetProperty("RotationMax", "Vector3D", "", 0, 0, 0)
    Me.SetProperty("RotationMinX", "bool", "", 0)
    Me.SetProperty("RotationMinY", "bool", "", 0)
    Me.SetProperty("RotationMinZ", "bool", "", 0)
    Me.SetProperty("RotationMaxX", "bool", "", 0)
    Me.SetProperty("RotationMaxY", "bool", "", 0)
    Me.SetProperty("RotationMaxZ", "bool", "", 0)
    Me.SetProperty("InheritType", "enum", "", 1)
    Me.SetProperty("ScalingActive", "bool", "", 0)
    Me.SetProperty("ScalingMin", "Vector3D", "", 1, 1, 1)
    Me.SetProperty("ScalingMax", "Vector3D", "", 1, 1, 1)
    Me.SetProperty("ScalingMinX", "bool", "", 0)
    Me.SetProperty("ScalingMinY", "bool", "", 0)
    Me.SetProperty("ScalingMinZ", "bool", "", 0)
    Me.SetProperty("ScalingMaxX", "bool", "", 0)
    Me.SetProperty("ScalingMaxY", "bool", "", 0)
    Me.SetProperty("ScalingMaxZ", "bool", "", 0)
    Me.SetProperty("GeometricTranslation", "Vector3D", "", 0, 0, 0)
    Me.SetProperty("GeometricRotation", "Vector3D", "", 0, 0, 0)
    Me.SetProperty("GeometricScaling", "Vector3D", "", 1, 1, 1)
    Me.SetProperty("MinDampRangeX", "double", "", 0)
    Me.SetProperty("MinDampRangeY", "double", "", 0)
    Me.SetProperty("MinDampRangeZ", "double", "", 0)
    Me.SetProperty("MaxDampRangeX", "double", "", 0)
    Me.SetProperty("MaxDampRangeY", "double", "", 0)
    Me.SetProperty("MaxDampRangeZ", "double", "", 0)
    Me.SetProperty("MinDampStrengthX", "double", "", 0)
    Me.SetProperty("MinDampStrengthY", "double", "", 0)
    Me.SetProperty("MinDampStrengthZ", "double", "", 0)
    Me.SetProperty("MaxDampStrengthX", "double", "", 0)
    Me.SetProperty("MaxDampStrengthY", "double", "", 0)
    Me.SetProperty("MaxDampStrengthZ", "double", "", 0)
    Me.SetProperty("PreferedAngleX", "double", "", 0)
    Me.SetProperty("PreferedAngleY", "double", "", 0)
    Me.SetProperty("PreferedAngleZ", "double", "", 0)
    Me.SetProperty("LookAtProperty", "object", "")
    Me.SetProperty("UpVectorProperty", "object", "")
    Me.SetProperty("Show", "bool", "", 1)
    Me.SetProperty("NegativePercentShapeSupport", "bool", "", 1)
    Me.SetProperty("DefaultAttributeIndex", "int", "", 0)
    Me.SetProperty("Freeze", "bool", "", 0)
    Me.SetProperty("LODBox", "bool", "", 0)
    Me.SetProperty("Lcl Translation", "Lcl Translation", "A+", 4.01245498657227, -3.21262097358704, -1.07940304279327)
    Me.SetProperty("Lcl Rotation", "Lcl Rotation", "A+", 79.0858932112017, -1.62263409563818, -52.5885703092691)
    Me.SetProperty("Lcl Scaling", "Lcl Scaling", "A+", 1, 1, 1)
    Me.SetProperty("Visibility", "Visibility", "A+", 1)
    Me.SetProperty("MaxHandle", "int", "UH", 1)
    Me.SetProperty("Position", "Vector", "A+N", 4.01245498657227, 1.07940304279327, -3.21262097358704)
    Me.SetProperty("UpVector", "Vector", "A+N", 0, 1, 0)
    Me.SetProperty("InterestPosition", "Vector", "A+N", 99.2882330109246, -123.484634586092, 1.22986222593592)
    Me.SetProperty("Roll", "Roll", "A+N", 0)
    Me.SetProperty("OpticalCenterX", "OpticalCenterX", "A+N", 0)
    Me.SetProperty("OpticalCenterY", "OpticalCenterY", "A+N", 0)
    Me.SetProperty("BackgroundColor", "Color", "A+N", 0.63, 0.63, 0.63)
    Me.SetProperty("TurnTable", "Number", "A+N", 0)
    Me.SetProperty("DisplayTurnTableIcon", "bool", "N", 0)
    Me.SetProperty("UseMotionBlur", "bool", "N", 0)
    Me.SetProperty("UseRealTimeMotionBlur", "bool", "N", 1)
    Me.SetProperty("Motion Blur Intensity", "Number", "A+N", 1)
    Me.SetProperty("AspectRatioMode", "enum", "N", 0)
    Me.SetProperty("AspectWidth", "double", "N", 640)
    Me.SetProperty("AspectHeight", "double", "N", 480)
    Me.SetProperty("PixelAspectRatio", "double", "N", 1)
    Me.SetProperty("FilmOffsetX", "Number", "A+N", 0)
    Me.SetProperty("FilmOffsetY", "Number", "A+N", 0)
    Me.SetProperty("FilmWidth", "double", "N", 1.41732287406921)
    Me.SetProperty("FilmHeight", "double", "N", 1.06299209594727)
    Me.SetProperty("FilmAspectRatio", "double", "N", 1.33333340809669)
    Me.SetProperty("FilmSqueezeRatio", "double", "N", 1)
    Me.SetProperty("FilmFormatIndex", "enum", "N", 0)
    Me.SetProperty("PreScale", "Number", "A+N", 1)
    Me.SetProperty("FilmTranslateX", "Number", "A+N", 0)
    Me.SetProperty("FilmTranslateY", "Number", "A+N", 0)
    Me.SetProperty("FilmRollPivotX", "Number", "A+N", 0)
    Me.SetProperty("FilmRollPivotY", "Number", "A+N", 0)
    Me.SetProperty("FilmRollValue", "Number", "A+N", 0)
    Me.SetProperty("FilmRollOrder", "enum", "N", 0)
    Me.SetProperty("ApertureMode", "enum", "N", 1)
    Me.SetProperty("GateFit", "enum", "N", 0)
    Me.SetProperty("FieldOfView", "FieldOfView", "A+N", 118.999981682544)
    Me.SetProperty("FieldOfViewX", "FieldOfViewX", "A+N", 40)
    Me.SetProperty("FieldOfViewY", "FieldOfViewY", "A+N", 40)
    Me.SetProperty("FocalLength", "Number", "A+N", 10.6028144661402)
    Me.SetProperty("CameraFormat", "enum", "N", 0)
    Me.SetProperty("UseFrameColor", "bool", "N", 0)
    Me.SetProperty("FrameColor", "ColorRGB", "N", 0.3, 0.3, 0.3)
    Me.SetProperty("ShowName", "bool", "N", 1)
    Me.SetProperty("ShowInfoOnMoving", "bool", "N", 1)
    Me.SetProperty("ShowGrid", "bool", "N", 1)
    Me.SetProperty("ShowOpticalCenter", "bool", "N", 0)
    Me.SetProperty("ShowAzimut", "bool", "N", 1)
    Me.SetProperty("ShowTimeCode", "bool", "N", 0)
    Me.SetProperty("ShowAudio", "bool", "N", 0)
    Me.SetProperty("AudioColor", "ColorRGB", "N", 0, 1, 0)
    Me.SetProperty("NearPlane", "double", "N", 10)
    Me.SetProperty("FarPlane", "double", "N", 4000)
    Me.SetProperty("AutoComputeClipPanes", "bool", "N", 1)
    Me.SetProperty("ViewCameraToLookAt", "bool", "N", 1)
    Me.SetProperty("ViewFrustumNearFarPlane", "bool", "N", 0)
    Me.SetProperty("ViewFrustumBackPlaneMode", "enum", "N", 2)
    Me.SetProperty("BackPlaneDistance", "Number", "A+N", 4000)
    Me.SetProperty("BackPlaneDistanceMode", "enum", "N", 1)
    Me.SetProperty("ViewFrustumFrontPlaneMode", "enum", "N", 2)
    Me.SetProperty("FrontPlaneDistance", "Number", "A+N", 10)
    Me.SetProperty("FrontPlaneDistanceMode", "enum", "N", 1)
    Me.SetProperty("LockMode", "bool", "N", 0)
    Me.SetProperty("LockInterestNavigation", "bool", "N", 0)
    Me.SetProperty("FitImage", "bool", "N", 0)
    Me.SetProperty("Crop", "bool", "N", 0)
    Me.SetProperty("Center", "bool", "N", 1)
    Me.SetProperty("KeepRatio", "bool", "N", 1)
    Me.SetProperty("BackgroundAlphaTreshold", "double", "N", 0.5)
    Me.SetProperty("ShowBackplate", "bool", "N", 1)
    Me.SetProperty("BackPlaneOffsetX", "Number", "A+N", 0)
    Me.SetProperty("BackPlaneOffsetY", "Number", "A+N", 0)
    Me.SetProperty("BackPlaneRotation", "Number", "A+N", 0)
    Me.SetProperty("BackPlaneScaleX", "Number", "A+N", 1)
    Me.SetProperty("BackPlaneScaleY", "Number", "A+N", 1)
    Me.SetProperty("Background Texture", "object", "N")
    Me.SetProperty("FrontPlateFitImage", "bool", "N", 1)
    Me.SetProperty("FrontPlateCrop", "bool", "N", 0)
    Me.SetProperty("FrontPlateCenter", "bool", "N", 1)
    Me.SetProperty("FrontPlateKeepRatio", "bool", "N", 1)
    Me.SetProperty("Foreground Opacity", "double", "N", 1)
    Me.SetProperty("ShowFrontplate", "bool", "N", 1)
    Me.SetProperty("FrontPlaneOffsetX", "Number", "A+N", 0)
    Me.SetProperty("FrontPlaneOffsetY", "Number", "A+N", 0)
    Me.SetProperty("FrontPlaneRotation", "Number", "A+N", 0)
    Me.SetProperty("FrontPlaneScaleX", "Number", "A+N", 1)
    Me.SetProperty("FrontPlaneScaleY", "Number", "A+N", 1)
    Me.SetProperty("Foreground Texture", "object", "N")
    Me.SetProperty("DisplaySafeArea", "bool", "N", 0)
    Me.SetProperty("DisplaySafeAreaOnRender", "bool", "N", 0)
    Me.SetProperty("SafeAreaDisplayStyle", "enum", "N", 1)
    Me.SetProperty("SafeAreaAspectRatio", "double", "N", 1.33333333333333)
    Me.SetProperty("Use2DMagnifierZoom", "bool", "N", 0)
    Me.SetProperty("2D Magnifier Zoom", "Number", "A+N", 100)
    Me.SetProperty("2D Magnifier X", "Number", "A+N", 50)
    Me.SetProperty("2D Magnifier Y", "Number", "A+N", 50)
    Me.SetProperty("CameraProjectionType", "enum", "N", 0)
    Me.SetProperty("OrthoZoom", "double", "N", 1)
    Me.SetProperty("UseRealTimeDOFAndAA", "bool", "N", 0)
    Me.SetProperty("UseDepthOfField", "bool", "N", 0)
    Me.SetProperty("FocusSource", "enum", "N", 0)
    Me.SetProperty("FocusAngle", "double", "N", 3.5)
    Me.SetProperty("FocusDistance", "double", "N", 200)
    Me.SetProperty("UseAntialiasing", "bool", "N", 0)
    Me.SetProperty("AntialiasingIntensity", "double", "N", 0.77777)
    Me.SetProperty("AntialiasingMethod", "enum", "N", 0)
    Me.SetProperty("UseAccumulationBuffer", "bool", "N", 0)
    Me.SetProperty("FrameSamplingCount", "int", "N", 7)
    Me.SetProperty("FrameSamplingType", "enum", "N", 1)
    Me.SetProperty("Color", "ColorRGB", "N", 0.337254901960784, 0.470588235294118, 0.8)
  End Sub


  Public Property ModelName() As String
    Get
      Return Me.sPiModelName
    End Get
    Set(ByVal value As String)
      Me.sPiModelName = value
      Me.SetValue("NodeAttributeName", """NodeAttribute::" & Me.ModelName & "_ncl1_1""")
    End Set
  End Property

  Public Sub SetPosition(ByVal X As Double, ByVal Y As Double, ByVal z As Double)
    Me.SetProperty("Lcl Translation", "Lcl Translation", "A+", X, Y, z)
    Me.SetValue("Position", CInt(X) & "," & CInt(Y) & "," & CInt(z))

  End Sub

  Public Sub SetRotation(ByVal X As Double, ByVal Y As Double, ByVal z As Double)
    Me.SetProperty("Lcl Rotation", "Lcl Rotation", "A+", X, Y, z)
  End Sub

  Public Sub SetTarget(ByVal X As Double, ByVal Y As Double, ByVal z As Double)
    Me.SetValue("LookAt", CInt(X) & "," & CInt(Y) & "," & CInt(z))
  End Sub
End Class
